package reviewops

import (
	"context"
	"fmt"
	"strings"
)

type TaskRunner interface {
	RunTask(context.Context, DraftInput) (*DraftResult, error)
}

type DraftInput struct {
	Task             Task
	SourceContext    *SourceContext
	SourceFetchError string
}

type DraftResult struct {
	Content string
}

type LocalDraftRunner struct{}

func (LocalDraftRunner) RunTask(ctx context.Context, input DraftInput) (*DraftResult, error) {
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Review Ops draft for %s #%d\n\n", input.Task.Repo, input.Task.TargetNumber)
	b.WriteString("This draft was generated by Eyrie's deterministic local review runner.\n\n")

	b.WriteString("## Target\n\n")
	fmt.Fprintf(&b, "- project_id: `%s`\n", input.Task.ProjectID)
	fmt.Fprintf(&b, "- kind: `%s`\n", input.Task.Kind)
	fmt.Fprintf(&b, "- repo: `%s`\n", input.Task.Repo)
	fmt.Fprintf(&b, "- target_number: `%d`\n", input.Task.TargetNumber)

	if input.SourceContext != nil {
		b.WriteString("\n## Source context summary\n\n")
		fmt.Fprintf(&b, "- title: %s\n", input.SourceContext.Title)
		fmt.Fprintf(&b, "- state: %s\n", input.SourceContext.State)
		fmt.Fprintf(&b, "- author: %s\n", input.SourceContext.Author)
		if input.SourceContext.URL != "" {
			fmt.Fprintf(&b, "- url: %s\n", input.SourceContext.URL)
		}
		if len(input.SourceContext.Labels) > 0 {
			fmt.Fprintf(&b, "- labels: %s\n", strings.Join(input.SourceContext.Labels, ", "))
		}
		if input.SourceContext.BodyExcerpt != "" {
			b.WriteString("\n### Body excerpt\n\n")
			b.WriteString(input.SourceContext.BodyExcerpt)
			b.WriteString("\n")
		}
		if len(input.SourceContext.Comments) > 0 {
			fmt.Fprintf(&b, "\n### Recent comments considered (%d)\n\n", len(input.SourceContext.Comments))
			for i, comment := range input.SourceContext.Comments {
				fmt.Fprintf(&b, "%d. %s: %s\n", i+1, comment.Author, comment.BodyExcerpt)
			}
		}
	}

	if input.SourceFetchError != "" {
		fmt.Fprintf(&b, "\n> **Source context fetch note**: %s\n", input.SourceFetchError)
	}

	b.WriteString("\n## Draft response\n\n")
	b.WriteString(draftResponse(input))
	b.WriteString("\n\n## Safety\n\n")
	b.WriteString("No GitHub mutations were performed. Review and approve exact public text before posting.\n")

	return &DraftResult{Content: b.String()}, nil
}

func draftResponse(input DraftInput) string {
	if input.SourceContext == nil {
		return "Source context was unavailable, so this draft is intentionally limited to the task metadata. Fetch context or inspect the target before posting."
	}

	switch input.Task.Kind {
	case "triage_issue":
		return fmt.Sprintf("Thanks for the report. I reviewed #%d and captured the current issue context for human triage. Next step is to confirm labels, priority, and whether this duplicates existing work before posting a public response.", input.Task.TargetNumber)
	case "review_pr":
		return fmt.Sprintf("I reviewed the available context for PR #%d. This draft is a starting point for a human PR review; inspect the diff and validation evidence before approving any public review.", input.Task.TargetNumber)
	case "rereview_pr":
		return fmt.Sprintf("I reviewed the refreshed context for PR #%d. This draft is a starting point for checking whether prior feedback was addressed; compare against earlier review threads before approving a public response.", input.Task.TargetNumber)
	case "respond_reviewer":
		return fmt.Sprintf("I reviewed the current context for PR #%d. This draft is a starting point for responding to reviewer feedback; verify each referenced concern against the latest code before posting.", input.Task.TargetNumber)
	default:
		return "I reviewed the available source context. Verify the target manually before posting any public response."
	}
}
